### ISSUE TITLE
Add Welcome page

### ISSUE THREAD

**Issue by Momaritti** [vincentrohde/iot_app#22]
We need a page in the routes directory for the welcomepage. On the Page we need the following components. See below design reference.

Welcome page components:

- Headline
- Teasertext
- CTAButton

<img width="721" alt="bildschirmfoto 2019-02-04 um 23 05 27" src="https://user-images.githubusercontent.com/27743279/52240549-69cf9b00-28d1-11e9-82e0-702f77432cc7.png">

**Comment by vincentrohde** [comment]
Already done with #7 
Needs some styling though.
